package edu.grinnell.csc207.soundsofsorting.sorts;

import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;

import edu.grinnell.csc207.soundsofsorting.sortevents.SortEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.CompareEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.CopyEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SwapEvent;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {
    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i the first index to swap
     * @param j the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> bubbleSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();

        for (int i = arr.length - 1; i > 0; i--) {
            for (int j = 0; j < i; j++) {
                events.add(new CompareEvent<>(j, j + 1));
                if (arr[j].compareTo(arr[j + 1]) > 0) {
                    events.add(new SwapEvent<>(j, j + 1));
                    swap(arr, j, j + 1);
                }
            }
        }

        return events;
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> selectionSort(
            T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();

        for (int i = 0; i < arr.length - 1; i++) {
            int minIndex = i;
            for (int j = i + 1; j < arr.length; j++) {
                events.add(new CompareEvent<>(j, minIndex));
                if (arr[j].compareTo(arr[minIndex]) < 0) {
                    minIndex = j;
                }
            }
            events.add(new SwapEvent<>(i, minIndex));
            swap(arr, i, minIndex);
        }

        return events;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * <pre>
     * [ i elements in order | unprocessed ] 
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> insertionSort(
            T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();

        for (int i = 1; i < arr.length; i++) {
            int j = i;
            while (j > 0) {
                events.add(new CompareEvent<>(j, j - 1));
                if (arr[j].compareTo(arr[j - 1]) < 0) {
                    events.add(new SwapEvent<>(j, j - 1));
                    swap(arr, j, j - 1);
                    j--;
                } else {
                    break;
                }
            }
        }

        return events;
    }

    /**
     * Sorts the array according to the merge sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> mergeSort(
            T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        T[] copy = Arrays.copyOf(arr, arr.length);
        mergeHelper(arr, copy, 0, arr.length, events);

        return events;
    }

    private static <T extends Comparable<? super T>> void mergeHelper(
            T[] arr, T[] copy, int lo, int hi, List<SortEvent<T>> events) {
        if (hi - lo <= 1) {
            return;
        }

        int mid = lo + (hi - lo) / 2;

        mergeHelper(arr, copy, lo, mid, events);
        mergeHelper(arr, copy, mid, hi, events);
        merge(arr, copy, lo, mid, hi, events);
    }

    private static <T extends Comparable<? super T>> void merge(
            T[] arr, T[] copy, int lo, int mid, int hi, List<SortEvent<T>> events) {
        for (int k = lo; k < hi; k++) {
            copy[k] = arr[k];
        }

        int i = lo;
        int j = mid;

        for (int k = lo; k < hi; k++) {
            if (i >= mid) {
                events.add(new CopyEvent<>(k, copy[j]));
                arr[k] = copy[j++];
            } else if (j >= hi) {
                events.add(new CopyEvent<>(k, copy[i]));
                arr[k] = copy[i++];
            } else {
                events.add(new CompareEvent<>(i, j));
                if (copy[i].compareTo(copy[j]) <= 0) {
                    events.add(new CopyEvent<>(k, copy[i]));
                    arr[k] = copy[i++];
                } else {
                    events.add(new CopyEvent<>(k, copy[j]));
                    arr[k] = copy[j++];
                }
            }
        }
    }

    /**
     * Sorts the array according to the quick sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> quickSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();

        quickSortHelper(arr, 0, arr.length - 1, events);

        return events;
    }

    private static <T extends Comparable<? super T>> void quickSortHelper(
            T[] arr, int start, int end, List<SortEvent<T>> events) {
        if (end <= start) {
            return;
        }

        int pivotIndex = partition(arr, start, end, events);
        quickSortHelper(arr, start, pivotIndex - 1, events);
        quickSortHelper(arr, pivotIndex + 1, end, events);
    }

    private static <T extends Comparable<? super T>> int partition(
            T[] arr, int start, int end, List<SortEvent<T>> events) {
        T pivot = arr[end];
        int i = start - 1;

        for (int j = start; j < end; j++) {
            events.add(new CompareEvent<>(j, end));
            if (arr[j].compareTo(pivot) < 0) {
                i++;
                events.add(new SwapEvent<>(i, j));
                swap(arr, i, j);
            }
        }

        i++;
        events.add(new SwapEvent<>(i, end));
        swap(arr, i, end);
        return i;
    }

    /**
     * Sorts the array according to the cocktail shaker sort algorithm:
     * <pre>
     * [ i smallest elements in order | unprocessed | i largest elements in order ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> cocktailShakerSort(
            T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();

        int start = 0;
        int end = arr.length - 1;
        boolean swapped = true;

        while (swapped) {
            swapped = false;

            // Forward pass: bubble the largest element to the end.
            for (int i = start; i < end; i++) {
                events.add(new CompareEvent<>(i, i + 1));
                if (arr[i].compareTo(arr[i + 1]) > 0) {
                    events.add(new SwapEvent<>(i, i + 1));
                    swap(arr, i, i + 1);
                    swapped = true;
                }
            }

            if (!swapped) {
                break;
            }

            swapped = false;
            end--;

            // Backward pass: bubble the smallest element to the start.
            for (int i = end; i > start; i--) {
                events.add(new CompareEvent<>(i - 1, i));
                if (arr[i - 1].compareTo(arr[i]) > 0) {
                    events.add(new SwapEvent<>(i - 1, i));
                    swap(arr, i - 1, i);
                    swapped = true;
                }
            }

            start++;
        }

        return events;
    }

    /**
     * Applies given events to the list in-order.
     * @param <T> the carrier type of the array
     * @param arr the array to apply events to
     * @param events the events to apply to the array
     */
    public static <T> void eventSort(T[] arr, List<SortEvent<T>> events) {
        for (SortEvent<T> e : events) {
            e.apply(arr);
        }
    }
}
